### ISSUE TITLE
Pokemon wont evolve.

### ISSUE THREAD

**Issue by Dynoooooooooooooooo** [NecronomiconCoding/NecroBot#1029]
All the pokemon I put in my Pokemonstoevolve list wont evolve.

{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\KaranS\\Downloads\\Bot3\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 52.379189,
  "DefaultLongitude": 4.899431,
  "DelayBetweenPokemonCatch": 100,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 50
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 25
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000000,
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew",
    "caterpie",
    "weedle",
    "pidgey",
    "doduo",
    "krabby",
    "psyduck",
    "rattata",
    "spearow",
    "zubat",
    "staryu"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "doduo",
    "krabby",
    "psyduck",
    "rattata",
    "spearow",
    "zubat",
    "staryu"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 800.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": true,
  "ProfilePath": "C:\\Users\\KaranS\\Downloads\\Bot3",
  "RenameAboveIv": true,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 0,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 120.0,
  "WebSocketPort": 14251
}

**Comment by tatakau** [comment]
same here. but with EvolveAllPokemonWithEnoughCandy

**Comment by braum123** [comment]
"EvolveAllPokemonWithEnoughCandy": false,
i have it on true and still dont evolve

**Comment by thenextfreud** [comment]
have you tried setting "KeepPokemonsThatCanEvolve": **true**

**Comment by tatakau** [comment]
yes tried "KeepPokemonsThatCanEvolve": true

**Comment by thenextfreud** [comment]
I'm having a similar issue, it's not transferring or evolving for me. I'm looking through the code right now.

**Comment by 5andr0** [comment]
We fixed all config related issues. Config pathing was broken. Make sure your config has the current write TimeStamp when starting

**Comment by tatakau** [comment]
working after update.

**Comment by guest136** [comment]
Am i doing something wrong, it still doesnt evolve fro the list?

{
  "AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\Armenia\\Downloads\\Neuer Bot\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 38.57813,
  "DefaultLongitude": -121.48671,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 50
    },
    {
      "Key": "itemMaxPotion",
      "Value": 100
    },
    {
      "Key": "itemRevive",
      "Value": 30
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "KeepMinCp": 1300,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 80.0,
  "KeepPokemonsThatCanEvolve": true,
  "MaxTravelDistanceInMeters": 1200,
  "PokemonsNotToTransfer": [
    "graveler",
    "pidgeotto",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "doduo",
    "weedle",
    "nidorina",
    "rattata",
    "spearow",
    "ekans",
    "sandshrew",
    "oddish",
    "zubat",
    "paras",
    "diglett",
    "growlithe",
    "poliwag",
    "machop",
    "bellsprout",
    "weedle",
    "tentacool",
    "geodude",
    "ponyta",
    "magnemite",
    "shellder",
    "drowzee",
    "krabby",
    "voltorb",
    "cubone",
    "goldeen",
    "pidgey"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Pidgeotto": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Fearow": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Golbat": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Eevee": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 2
    },
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10
    }
  },
  "PrioritizeIvOverCp": true,
  "ProfilePath": "C:\\Users\\Armenia\\Downloads\\Neuer Bot\\NecroBot-master\\PoGo.NecroBot.CLI\\bin\\Debug",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251
}
